functionsDirectory = "C:\\Users\\Win11\\Downloads\\Documents\\Website Raskop\\netlify\\functions"
functionsDirectoryOrigin = "config"
redirectsOrigin = "config"
plugins = []
headers = []

[build]
publish = "C:\\Users\\Win11\\Downloads\\Documents\\Website Raskop"
publishOrigin = "config"
functions = "C:\\Users\\Win11\\Downloads\\Documents\\Website Raskop\\netlify\\functions"

[build.environment]
NODE_VERSION = "18"

[build.processing]

[build.processing.css]

[build.processing.html]

[build.processing.images]

[build.processing.js]

[build.services]

[functions]

[functions."*"]

[[redirects]]
from = "/reservasi"
to = "/reservasi.html"
status = 200.0
force = false

[redirects.query]

[redirects.conditions]

[redirects.headers]

[[redirects]]
from = "/admin"
to = "/admin.html"
status = 200.0
force = false

[redirects.query]

[redirects.conditions]

[redirects.headers]

[[redirects]]
from = "/menu"
to = "/menu.html"
status = 200.0
force = false

[redirects.query]

[redirects.conditions]

[redirects.headers]